<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;

class RealTanosProjectSeeder extends Seeder
{
    public function run(): void
    {
        $realProjects = [
            [
                'project_code' => 'S/PS-2024-01-00001',
                'id_project_humanis' => '93',
                'project_name' => 'TAD - REG3 - JOPRO SUB REGIONAL JAWA',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0091',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Tanjung Emas',
                'regional_unit' => 'Regional PDS Jawa',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Subreg Jawa - Tanjung Perak',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 12500000000,
                'active' => 1,
            ],
            [
                'project_code' => 'S/PS-2024-01-00002',
                'id_project_humanis' => '94',
                'project_name' => 'TAD - REG3 - JOPRO TANJUNG EMAS',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0092',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Tanjung Emas',
                'regional_unit' => 'Regional PDS Jawa',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Pelabuhan Tanjung Emas',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 8400000000,
                'active' => 1,
            ],
            [
                'project_code' => 'S/PS-2024-01-00003',
                'id_project_humanis' => '97',
                'project_name' => 'TAD - REG3 - JOPRO TANJUNG INTAN',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0093',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Tanjung Intan',
                'regional_unit' => 'Regional PDS Jawa',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Pelabuhan Tanjung Intan Cilacap',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 6200000000,
                'active' => 1,
            ],
            [
                'project_code' => 'S/PS-2024-01-00004',
                'id_project_humanis' => '98',
                'project_name' => 'TAD - REG3 - JOPRO CELUKAN BAWANG',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0094',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Celukan Bawang',
                'regional_unit' => 'Regional PDS Bali Nusa Tenggara',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Pelabuhan Celukan Bawang',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 4500000000,
                'active' => 1,
            ],
            [
                'project_code' => 'S/PS-2024-01-00005',
                'id_project_humanis' => '99',
                'project_name' => 'TAD - REG3 - JOPRO MAUMERE',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0095',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Maumere',
                'regional_unit' => 'Regional PDS Bali Nusa Tenggara',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Pelabuhan Maumere',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 3800000000,
                'active' => 1,
            ],
            [
                'project_code' => 'S/PS-2024-01-00006',
                'id_project_humanis' => '101',
                'project_name' => 'TAD - REG3 - JOPRO TANJUNG TEMBAGA',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0096',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Probolinggo',
                'regional_unit' => 'Regional PDS Jawa',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Pelabuhan Tanjung Tembaga',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 5100000000,
                'active' => 1,
            ],
            [
                'project_code' => 'S/PS-2024-01-00007',
                'id_project_humanis' => '103',
                'project_name' => 'TAD - REG3 - JOPRO KOTABARU',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0097',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Kotabaru',
                'regional_unit' => 'Regional PDS Kalimantan',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Pelabuhan Kotabaru Batulicin',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 7300000000,
                'active' => 1,
            ],
            [
                'project_code' => 'S/PS-2024-01-00008',
                'id_project_humanis' => '104',
                'project_name' => 'TAD - REG3 - JOPRO GRESIK',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0098',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Gresik',
                'regional_unit' => 'Regional PDS Jawa',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Pelabuhan Gresik',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 9600000000,
                'active' => 1,
            ],
            [
                'project_code' => 'S/PS-2024-01-00009',
                'id_project_humanis' => '106',
                'project_name' => 'TAD - REG3 - JOPRO KUMAI',
                'description' => 'Tenaga Alih Daya',
                'customer_name' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'vendor' => 'PT Pelabuhan Indonesia (Persero) Regional 3',
                'contract_number' => 'OA-2024-0099',
                'project_category' => '01. Tenaga Alih Daya Operasional',
                'contract_type' => 'NON-JOPRO',
                'location' => 'Kumai',
                'regional_unit' => 'Regional PDS Kalimantan',
                'unit_kerja' => 'PT Pelabuhan Indonesia (Persero) Regional 3 - Pelabuhan Kumai',
                'start_date' => '2025-02-19',
                'end_date' => '2025-12-31',
                'validity_start' => '2020-01-01',
                'validity_end' => '2024-12-31',
                'month' => 'Januari 2026',
                'regional' => 'Regional 3',
                'segment' => 'TAD Operasional',
                'cost' => 4900000000,
                'active' => 1,
            ],
        ];

        foreach ($realProjects as $pData) {
            Project::updateOrCreate(
                ['project_code' => $pData['project_code']],
                $pData
            );
        }
    }
}
